### ISSUE TITLE
failed requests not detected and handled gracefully

### ISSUE THREAD

**Issue by nickolasclarke** [icodeforlove/doapi#8]
```
TypeError: Cannot read property 'headers' of undefined
    at Request._callback (/home/nick/repos/test/node_modules/doapi/index.js:100:20)
    at self.callback (/home/nick/repos/test/node_modules/doapi/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestError (/home/nick/repos/test/node_modules/doapi/node_modules/request/request.js:820:8)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at Socket.onerror (tls.js:1445:17)
    at Socket.EventEmitter.emit (events.js:117:20)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
```

**Comment by icodeforlove** [comment]
can you install `0.1.2`, and tell me if this continues.

also  why was the request failing?

**Comment by nickolasclarke** [comment]
@icodeforlove I'm based in china, and connections to DO timeout all the time for various reasons. :/ 

whoops, hit return too soon. Testing by kililing the network to my dev VM now results in the following: 

```
 Unhandled rejection Error: Request Failed: Error: getaddrinfo ENOTFOUND
     at Request._callback (/home/nick/repos/test/node_modules/doapi/index.js:119:23)
     at self.callback (/home/nick/repos/test/node_modules/doapi/node_modules/request/request.js:199:22)
     at Request.EventEmitter.emit (events.js:95:17)
     at Request.onRequestError (/home/nick/repos/test/node_modules/doapi/node_modules/request/request.js:821:8)
     at ClientRequest.EventEmitter.emit (events.js:95:17)
     at CleartextStream.socketErrorListener (http.js:1547:9)
     at CleartextStream.EventEmitter.emit (events.js:95:17)
     at Socket.onerror (tls.js:1445:17)
     at Socket.EventEmitter.emit (events.js:117:20)
     at net.js:830:16
     at process._tickCallback (node.js:415:13)
```

but at least it doesnt crash node. I'm not sure how far down the hole you want to go for handling request errors.

**Comment by nickolasclarke** [comment]
@icodeforlove looking further down the code, it seems you do handle this in an acceptable fashion. 6575ac14f seems to resolve the issue.

**Comment by icodeforlove** [comment]
Yeah, even on digital oceans own network i was getting request errors (sub 1%). Best of luck, and thanks for finding this.
